name: Build, Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests Whyfate.Toolkit.Tests with coverage
        run: dotnet test tests/Whyfate.Toolkit.Tests/Whyfate.Toolkit.Tests.csproj --collect:"XPlat Code Coverage"

      # - name: Run tests Whyfate.Toolkit.Other.Tests project with coverage
      #  run: dotnet test tests/Whyfate.Toolkit.Other.Tests/Whyfate.Toolkit.Other.Tests.csproj --collect:"XPlat Code Coverage"

      - name: Install reportgenerator tool
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate coverage report
        run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report